m4-w1d2-csharp-history-geek-exercises/HistoryGeek.Web/Controllers/ChatController.cs
using HistoryGeek.Web.DataAccess;
using HistoryGeek.Web.Models;
using HistoryGeek.Web.Models.ViewModels;
using Microsoft.AspNet.SignalR;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HistoryGeek.Web.Controllers
{
    // Chat Controller manages the logic for displaying chat history and saving chat messages.
    public class ChatController : Controller
    {
        private readonly IChatHistoryDAL chatHistoryDal;
        private readonly IUserDAL userDal;

        public ChatController(IChatHistoryDAL chatHistoryDal, IUserDAL userDal)
        {
            this.chatHistoryDal = chatHistoryDal;
            this.userDal = userDal;
        }

        // Used to make sure that the user has "logged in" before chatting.
        //protected override void OnActionExecuting(ActionExecutingContext filterContext)
        //{
        //    if (Session[SessionKeys.Username] == null)
        //    {
        //        filterContext.Result = RedirectToAction("Login", "User");
        //    }
        //}

        // GET: Chat/
        // Users must have logged in to visit the chat page.
        [System.Web.Mvc.Authorize]
        public ActionResult Index()
        {
            List<ChatMessage> messages = chatHistoryDal.GetChatMessages(20); //last 20 chat messages
            return View("Index", messages);
        }

        // POST: Chat/
        [HttpPost]
        [System.Web.Mvc.Authorize]
        public ActionResult Index(string message)
        {
            if (!String.IsNullOrEmpty(message))
            {
                // Get the user who sent in the request
                User user = userDal.GetUser((string)Session[SessionKeys.Username]);
                ChatMessage chatMessage = new ChatMessage()
                {
                    Message = message,
                    UserId = user.Id,
                    Username = user.Email,
                    SentDate = DateTime.UtcNow
                };

                // Save the chat message
                chatHistoryDal.SaveChatMessage(chatMessage);

                // Use the SignalR library to "Broadcast" the message to all listening users
                var chatConnectionContext = GlobalHost.ConnectionManager.GetConnectionContext<ChatConnection>();
                var broadcastMessage = new
                {
                    type = "newmessage",
                    values = chatMessage
                };
                chatConnectionContext.Connection.Broadcast(broadcastMessage);
            }

            return RedirectToAction("Index");
        }


    }
}

m4-w1d2-csharp-history-geek-exercises/HistoryGeek.Web/Views/Chat/Index.cshtml
@using HistoryGeek.Web.Models;
@model List<ChatMessage>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/exercises/websocket-exercises.js"></script>

<div id="chatroom">

    <div id="messages">
        <h3>History</h3>
        <!-- Messages go here -->
        <div id="history">
            @foreach (var message in Model)
            {
                <p class="message">
                    <span class="username">@message.Username</span> <span class="time">@message.SentDate.ToShortTimeString()</span> <br />
                    @message.Message
                </p>
            }
        </div>
        <div id="newMessageForm">
            @using (Html.BeginForm("Index", "Chat", FormMethod.Post))
            {                
                @Html.TextArea("message", new { placeholder = "message" })
                <button>SEND</button>
            }
        </div>
    </div>
    <div id="members">
        <h3>Active Members</h3>
        <!-- Members List goes here -->
        <ul>            
        </ul>
    </div>
</div>