m3-w2d2-controllers-part1-exercises/GetExercises.Web/Models/Actor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GetExercises.Web.Models
{
    public class Actor
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}

m3-w2d2-controllers-part1-exercises/GetExercises.Web/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GetExercises.Web.Models
{
    public class Customer
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public bool IsActive { get; set; }
    }
}

m3-w2d2-controllers-part1-exercises/GetExercises.Web/Models/Film.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GetExercises.Web.Models
{
    public class Film
    {
        public string Title { get; set; }
        public string Description { get; set; }
        public int ReleaseYear { get; set; }
        public int Length { get; set; }
        public string Rating { get; set; }
    }
}

m3-w2d2-controllers-part1-exercises/GetExercises.Web/Models/FilmSearchViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GetExercises.Web.Models
{
    public class FilmSearchViewModel
    {
        public string Genre { get; set; }

        public int? MinLength { get; set; }

        public int? MaxLength { get; set; }
    }
}

m3-w2d2-controllers-part1-exercises/GetExercises.Web/Controllers/ActorController.cs
using GetExercises.Web.DAL.Interfaces;
using GetExercises.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GetExercises.Web.Controllers
{
    public class ActorController : Controller
    {
        private IActorDAL dal;
        // EAU - is above supposed to be private? Example has no private/public association
        /// <summary>
        /// The MVC framework with the assistance of Ninject, automatically passes in a ActorDAL.
        /// </summary>
        /// <param name="dal"></param>
        public ActorController(IActorDAL dal)
        {
            this.dal = dal;
        }
        
        /// <summary>
        /// The request to display an empty search page.
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// The request to display search results.
        /// </summary>
        /// <param name="request">A request model that contains the search parameters.</param>
        /// <returns></returns>
        //public ActionResult SearchResult(/*ActorSearch request */)
        public ActionResult SearchResult(string Name)
        {
            /* Call the DAL and pass the values as a model back to the View */
            //return null;
            IList<Actor> actorList = dal.FindActors(Name);
           
            return View("SearchResult", actorList);
        }
    }
}

m3-w2d2-controllers-part1-exercises/GetExercises.Web/Controllers/CustomerController.cs
using GetExercises.Web.DAL.Interfaces;
using GetExercises.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GetExercises.Web.Controllers
{
    public class CustomerController : Controller
    {
        private ICustomerDAL dal;

        /// <summary>
        /// The MVC framework with the assistance of Ninject, automatically passes in a CustomerDAL.
        /// </summary>
        /// <param name="dal"></param>
        public CustomerController(ICustomerDAL dal)
        {
            this.dal = dal;
        }

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult SearchResult(string name, string sortBy)
        {
            /* Call the DAL and pass the values as a model back to the View */
            IList<Customer> customerList = dal.SearchForCustomers(name, sortBy);

            return View("SearchResult", customerList);
        }

    }
}

m3-w2d2-controllers-part1-exercises/GetExercises.Web/Controllers/FilmController.cs
using GetExercises.Web.DAL.Interfaces;
using GetExercises.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GetExercises.Web.Controllers
{
    public class FilmController : Controller
    {
        private IFilmDAL dal;

        /// <summary>
        /// The MVC framework with the assistance of Ninject, automatically passes in a FilmDAL.
        /// </summary>
        /// <param name="dal"></param>
        public FilmController(IFilmDAL dal)
        {
            this.dal = dal;
        }

        /// <summary>
        /// The request to display an empty search page.
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View("Index2");
        }

        /// <summary>
        /// Receives the search result request and goes to th database looking for the information.
        /// </summary>
        /// <param name="request">A request model that contains the search parameters.</param>
        /// <returns></returns>
        //public ActionResult SearchResult(/*FilmSearch request */)
        //public ActionResult SearchResult(string genre, int? minLength, int? maxLength)
        //{
        //    //IList<Film> filmlist = dal.GetFilmsBetween(film.Length);

        //    IList<Film> filmList = dal.GetFilmsBetween(genre, minLength?? 0, maxLength?? 60*24);

        //    return View("SearchResult", filmList);
        //    /* Call the DAL and pass the values as a model back to the View */
        //}
        public ActionResult SearchResult(FilmSearchViewModel filmSearch)
        {
            //IList<Film> filmlist = dal.GetFilmsBetween(film.Length);

            IList<Film> filmList = dal.GetFilmsBetween(filmSearch.Genre, filmSearch.MinLength?? 0, filmSearch.MaxLength?? 60 * 24);

            return View("SearchResult", filmList);
            /* Call the DAL and pass the values as a model back to the View */
        }
    }
}

m3-w2d2-controllers-part1-exercises/GetExercises.Web/Views/Actor/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Actor Search </h2>


@using (Html.BeginForm("SearchResult", "Actor", FormMethod.Get, new { id = "search-form" })) 
{

    
<div class="form-horizontal">
    <h4> Index View </h4>
    <hr />
    


    <div class="form-group">
        @Html.Label("Name:", htmlAttributes: new { @class = "control-label col-md-2" })
       
        <div class="col-md-10">
            @Html.TextBox("Name", null, new { @class = "form-control" })
            
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Search" class="btn btn-default" />
        </div>
    </div>
</div>
}


<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

m3-w2d2-controllers-part1-exercises/GetExercises.Web/Views/Actor/SearchResult.cshtml
@*Bind to IList<Actor> *@

@model IList<GetExercises.Web.Models.Actor>


@{
    ViewBag.Title = "SearchResult";
}

<style>
    .page-header {
        font-size: small;
        font-weight: 700;
    }
</style>

<h2>Actor Search Results...</h2>
<table class="table">

    <tr>
        <td class="page-header">First Name</td>
        <td class="page-header">Last Name</td>

    @foreach (var actor in Model)
    {
        <tr>
            <td>@actor.FirstName</td>
            <td>@actor.LastName</td>
        </tr>
    }
</table>

m3-w2d2-controllers-part1-exercises/GetExercises.Web/Views/Customer/Index.cshtml
@{
    ViewBag.Title = "Index";

    List<SelectListItem> categoryList = new List<SelectListItem>
    { 
    new SelectListItem {Text = "Last Name", Value = "name"},
    new SelectListItem {Text = "E-Mail", Value = "email" },
    new SelectListItem {Text ="Active Status", Value = "active"},
    };
}

<h2>Customer Search</h2>

@using (Html.BeginForm("SearchResult", "Customer", FormMethod.Get, new { id = "search-form" }))
{
<div class="form-horizontal">
    <h4> Index View </h4>
    <hr />

   
    <div class="form-group">

        @Html.Label("Name:", htmlAttributes: new { @class = "control-label col-md-2" })


        <div class="col-md-10">
            @Html.TextBox("Name", null, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">

        @Html.Label("Sort By:", htmlAttributes: new { @class = "control-label col-md-2" })


        <div class="col-md-10">
            @Html.DropDownList("sortBy", categoryList)
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Search" class="btn btn-default" />
        </div>
    </div>
</div>
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

m3-w2d2-controllers-part1-exercises/GetExercises.Web/Views/Customer/SearchResult.cshtml
@model IList<GetExercises.Web.Models.Customer>

@{
    ViewBag.Title = "SearchResult";
}
<style>
    .page-header {
        font-size: small;
        font-weight: 700;
    }
</style>

<h2>Customer Search Results</h2>

<table class="table">

        <tr>
            <td class="page-header">First Name</td>
            <td class="page-header">Last Name</td>
            <td class="page-header">E-mail</td>
            <td class="page-header">Active?</td>
        </tr>
        @foreach (var customer in Model)
        {
            <tr>
                <td>@customer.FirstName</td>
                <td>@customer.LastName</td>
                <td>@customer.Email</td>
                <td>@customer.IsActive</td>
            </tr>
        }
    </table>

m3-w2d2-controllers-part1-exercises/GetExercises.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Blockbuster Rentals", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>