UPDATED_m3-w2d4-ssgeek-session-exercise/SSGeek/Controllers/CalculatorsController.cs
using SSGeek.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SSGeek.Controllers
{
    public class CalculatorsController : Controller
    {
        // INSTRUCTIONS
        // As a part of each exercise you will need to 
        // - develop a view for AlienAge, AlienWeight, and AlienTravel that displays a form to submit data
        // - develop a model for the forms to bind to when the form request is submitted
        // - create a new action to process the form submission (e.g. AlienAgeResult, AlienWeightResult, etc.)
        // - create a view that displays the submitted form result

        // GET: Calculators/AlienAge
        public ActionResult AlienAge()
        {            
            return View("AlienAge");
        }

        public ActionResult AlienAgeResult(AlienAgeModel model)
        {            
            return View("AlienAgeResult", model);
        }
        
        //TODO: Create an AlienWeight and AlienWeightResult Action
        //TODO: Create an AlienTravel and AlienTravelResult Action

        

        private List<SelectListItem> transportationModes = new List<SelectListItem>()
        {
            new SelectListItem() { Text = "Walking", Value="walking" },
            new SelectListItem() { Text = "Car", Value = "car" },
            new SelectListItem() { Text = "Bullet Train", Value = "bullet train" },
            new SelectListItem() { Text = "Boeing 747", Value = "boeing 747" },
            new SelectListItem() { Text = "Concorde", Value = "concorde" }
        };
    }
}

UPDATED_m3-w2d4-ssgeek-session-exercise/SSGeek/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SSGeek.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return RedirectToAction("Index", "Planets"); //<-- if user goes to .com/ this redirects to .com/planets/index
        }
    }
}

UPDATED_m3-w2d4-ssgeek-session-exercise/SSGeek/Controllers/PlanetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SSGeek.Controllers
{
    public class PlanetsController : Controller
    {
        // GET: Planets
        public ActionResult Index()
        {
            return View("Index");
        }
    }
}

UPDATED_m3-w2d4-ssgeek-session-exercise/SSGeek/Controllers/ShoppingCartController.cs
using SSGeek.Models;
using SSGeek.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SSGeek.Controllers
{
    public class ShoppingCartController : Controller
    {
        private IProductDAL productDAL;

        private const string ShoppingCart_SessionKey = "ShoppingCart";


        public ShoppingCartController(IProductDAL productDAL)
        {
            this.productDAL = productDAL;
        }

        // GET: ShoppingCart
        [HttpGet]
        public ActionResult Index()
        {
            List<Product> products = productDAL.GetProducts();
            return View("Index", products);
        }

        // GET: Item Details
        [HttpGet]
        public ActionResult Detail(int id)
        {
            Product item = productDAL.GetProduct(id);
            if ((item == null) || (item.ProductId != id))
            {
                return new HttpNotFoundResult();
                //404
            }          
            return View("Detail", item);
        }

        // POST: Add Item to Cart
        [HttpPost]
        public ActionResult UpdateCart (Product specificItem, int quantity)
        {
            Product item = productDAL.GetProduct(specificItem.ProductId);
            if ((item == null) || (item.ProductId!= specificItem.ProductId))
            {
                return new HttpNotFoundResult();
                //404
            }
            if (Session[ShoppingCart_SessionKey] == null)
            {
                Session[ShoppingCart_SessionKey] = new ShoppingCartView();
            }

            var shoppingCart = Session[ShoppingCart_SessionKey] as ShoppingCartView;

            shoppingCart.UpdateCart(specificItem, quantity);

            Session[ShoppingCart_SessionKey] = shoppingCart;

            return RedirectToAction("ViewCart", "ShoppingCart");
        }

        //GET: ViewCart
        [HttpGet]
        public ActionResult ViewCart()
        {
            ShoppingCartView model = new ShoppingCartView();

            if (Session[ShoppingCart_SessionKey] != null)
            {
                model = (ShoppingCartView)Session[ShoppingCart_SessionKey];
            }
            return View("ViewCart", model);
        }

    }
}

UPDATED_m3-w2d4-ssgeek-session-exercise/SSGeek/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Solar System Geek</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="~/Content/solarsystemgeek.css">
</head>

<body>
    <header>
        <img src="~/Content/img/ssg_logo.png" alt="Solar System Geek logo" />
        <h1>The Solar System</h1>
        <p>The Solar System formed 4.6 billion years ago from the gravitational collapse of a giant interstellar molecular cloud. The vast majority of the system's mass is in the Sun, with most of the remaining mass contained in Jupiter. The four smaller inner planets, Mercury, Venus, Earth and Mars, are terrestrial planets, being primarily composed of rock and metal. The four outer planets are giant planets, being substantially more massive than the terrestrials. The two largest, Jupiter and Saturn, are gas giants, being composed mainly of hydrogen and helium; the two outermost planets, Uranus and Neptune, are ice giants, being composed largely of substances with relatively high melting points compared with hydrogen and helium, called ices, such as water, ammonia and methane. All planets have almost circular orbits that lie within a nearly flat disc called the ecliptic. </p>
    </header>
    <nav>
        <h2>Explore The Solar System</h2>
        <p> Use these state of the art web applications to learn more about the solar system! </p>
        <ul>
            <li>@Html.ActionLink("Alien Age", "AlienAge", "Calculators")</li>
            <li>@Html.ActionLink("Alien Weight", "AlienWeight", "Calculators")</li>
            <li>@Html.ActionLink("Alien Travel Time", "AlienTravel", "Calculators")</li>
            <li>@Html.ActionLink("Space Forum", "Index", "Forum")</li>
            <li>@Html.ActionLink("Space Store", "Index", "ShoppingCart")</li>

        </ul>
    </nav>
    <section id="centeredPanel">
        @RenderBody()
        </section>
</body>
</html>